language: node_js
node_js:
  - 'lts/*'
install:
  - npm ci
  - npm install codecov -g
script:
  - npm run prettier:check
  - npm run lint:check
  - npm run test:ci
  - npm run build
after_success:
  - codecov -f ./coverage/clover.xml
before_deploy:
  - cp package.json build/package.json
  - cp LICENSE build/LICENSE
  - cp README.md build/README.md
  - cp CHANGELOG.md build/CHANGELOG.md
  - cd build
# deploy:
#   provider: npm
#   email: attila.olah@outlook.com
#   api_key:
#     secure: $NPM_PUBLISH_TOKEN
#   on:
#     branch: master
#   skip_cleanup: true
